// reference: https://zh.wikipedia.org/zh-tw/Unicode%E5%8D%80%E6%AE%B5

var unicodeInfo = [
    { plane:'0 BMP',	codeStart:'U+0000',	codeEnd:'U+007F',	nameCht:'基本拉丁字母',	nameEng:'Basic Latin[g]',	description:'拉丁字母（52個）、通用（76個）' },
    { plane:'0 BMP',	codeStart:'U+0080',	codeEnd:'U+00FF',	nameCht:'拉丁字母補充-1',	nameEng:'Latin-1 Supplement[h]',	description:'拉丁字母（64個）、通用（64個）' },
    { plane:'0 BMP',	codeStart:'U+0100',	codeEnd:'U+017F',	nameCht:'拉丁字母擴展-A',	nameEng:'Latin Extended-A',	description:'拉丁' },
    { plane:'0 BMP',	codeStart:'U+0180',	codeEnd:'U+024F',	nameCht:'拉丁字母擴展-B',	nameEng:'Latin Extended-B',	description:'拉丁' },
    { plane:'0 BMP',	codeStart:'U+0250',	codeEnd:'U+02AF',	nameCht:'國際音標擴展',	nameEng:'IPA Extensions',	description:'拉丁' },
    { plane:'0 BMP',	codeStart:'U+02B0',	codeEnd:'U+02FF',	nameCht:'佔位修飾符號',	nameEng:'Spacing Modifier Letters',	description:'注音符號（2個）、拉丁（14個）、通用（64個）' },
    { plane:'0 BMP',	codeStart:'U+0300',	codeEnd:'U+036F',	nameCht:'組合附加符號',	nameEng:'Combining Diacritical Marks',	description:'繼承' },
    { plane:'0 BMP',	codeStart:'U+0370',	codeEnd:'U+03FF',	nameCht:'希臘字母和科普特字母',	nameEng:'Greek and Coptic',	description:'科普特字母（14個）、希臘字母（117個）、通用（4個）' },
    { plane:'0 BMP',	codeStart:'U+0400',	codeEnd:'U+04FF',	nameCht:'西里爾字母',	nameEng:'Cyrillic',	description:'西里爾字母（254個）、繼承（2個）' },
    { plane:'0 BMP',	codeStart:'U+0500',	codeEnd:'U+052F',	nameCht:'西里爾字母補充',	nameEng:'Cyrillic Supplement',	description:'西里爾字母' },
    { plane:'0 BMP',	codeStart:'U+0530',	codeEnd:'U+058F',	nameCht:'亞美尼亞字母',	nameEng:'Armenian',	description:'亞美尼亞字母' },
    { plane:'0 BMP',	codeStart:'U+0590',	codeEnd:'U+05FF',	nameCht:'希伯來文字母',	nameEng:'Hebrew',	description:'希伯來字母' },
    { plane:'0 BMP',	codeStart:'U+0600',	codeEnd:'U+06FF',	nameCht:'阿拉伯文字母',	nameEng:'Arabic',	description:'阿拉伯字母（238個）、通用（6個）、繼承（12個）' },
    { plane:'0 BMP',	codeStart:'U+0700',	codeEnd:'U+074F',	nameCht:'敘利亞字母',	nameEng:'Syriac',	description:'敘利亞字母' },
    { plane:'0 BMP',	codeStart:'U+0750',	codeEnd:'U+077F',	nameCht:'阿拉伯文補充',	nameEng:'Arabic Supplement',	description:'阿拉伯文' },
    { plane:'0 BMP',	codeStart:'U+0780',	codeEnd:'U+07BF',	nameCht:'它拿字母',	nameEng:'Thaana',	description:'它拿字母' },
    { plane:'0 BMP',	codeStart:'U+07C0',	codeEnd:'U+07FF',	nameCht:'西非書面文字',	nameEng:'NKo',	description:'西非書面文字' },
    { plane:'0 BMP',	codeStart:'U+0800',	codeEnd:'U+083F',	nameCht:'撒瑪利亞字母',	nameEng:'Samaritan',	description:'撒瑪利亞字母' },
    { plane:'0 BMP',	codeStart:'U+0840',	codeEnd:'U+085F',	nameCht:'曼達安字母',	nameEng:'Mandaic',	description:'曼達安字母' },
    { plane:'0 BMP',	codeStart:'U+0860',	codeEnd:'U+086F',	nameCht:'敘利亞文補充',	nameEng:'Syriac Supplement',	description:'敘利亞文' },
    { plane:'0 BMP',	codeStart:'U+0870',	codeEnd:'U+089F',	nameCht:'阿拉伯字母擴展-B',	nameEng:'Arabic Extended-B',	description:'阿拉伯字母' },
    { plane:'0 BMP',	codeStart:'U+08A0',	codeEnd:'U+08FF',	nameCht:'阿拉伯字母擴展-A',	nameEng:'Arabic Extended-A',	description:'阿拉伯字母（95個）、通用（1個）' },
    { plane:'0 BMP',	codeStart:'U+0900',	codeEnd:'U+097F',	nameCht:'天城文',	nameEng:'Devanagari',	description:'天城文（122個）、通用（2個）、繼承（4個）' },
    { plane:'0 BMP',	codeStart:'U+0980',	codeEnd:'U+09FF',	nameCht:'孟加拉文',	nameEng:'Bengali',	description:'孟加拉文' },
    { plane:'0 BMP',	codeStart:'U+0A00',	codeEnd:'U+0A7F',	nameCht:'古木基文',	nameEng:'Gurmukhi',	description:'古木基文' },
    { plane:'0 BMP',	codeStart:'U+0A80',	codeEnd:'U+0AFF',	nameCht:'古吉拉特文',	nameEng:'Gujarati',	description:'古吉拉特文' },
    { plane:'0 BMP',	codeStart:'U+0B00',	codeEnd:'U+0B7F',	nameCht:'奧里亞文',	nameEng:'Oriya',	description:'奧里亞文' },
    { plane:'0 BMP',	codeStart:'U+0B80',	codeEnd:'U+0BFF',	nameCht:'泰米爾文',	nameEng:'Tamil',	description:'泰米爾文' },
    { plane:'0 BMP',	codeStart:'U+0C00',	codeEnd:'U+0C7F',	nameCht:'泰盧固文',	nameEng:'Telugu',	description:'泰盧固文' },
    { plane:'0 BMP',	codeStart:'U+0C80',	codeEnd:'U+0CFF',	nameCht:'卡納達文',	nameEng:'Kannada',	description:'卡納達文' },
    { plane:'0 BMP',	codeStart:'U+0D00',	codeEnd:'U+0D7F',	nameCht:'馬拉雅拉姆文',	nameEng:'Malayalam',	description:'馬拉雅拉姆文' },
    { plane:'0 BMP',	codeStart:'U+0D80',	codeEnd:'U+0DFF',	nameCht:'僧伽羅文',	nameEng:'Sinhala',	description:'僧伽羅文' },
    { plane:'0 BMP',	codeStart:'U+0E00',	codeEnd:'U+0E7F',	nameCht:'泰文',	nameEng:'Thai',	description:'泰文（86個）、通用（1個）' },
    { plane:'0 BMP',	codeStart:'U+0E80',	codeEnd:'U+0EFF',	nameCht:'寮文',	nameEng:'Lao',	description:'寮文' },
    { plane:'0 BMP',	codeStart:'U+0F00',	codeEnd:'U+0FFF',	nameCht:'藏文',	nameEng:'Tibetan',	description:'藏文字母（207個）、通用（4個）' },
    { plane:'0 BMP',	codeStart:'U+1000',	codeEnd:'U+109F',	nameCht:'緬甸文',	nameEng:'Myanmar',	description:'緬文' },
    { plane:'0 BMP',	codeStart:'U+10A0',	codeEnd:'U+10FF',	nameCht:'喬治亞字母',	nameEng:'Georgian',	description:'喬治亞字母（87個）、通用（1個）' },
    { plane:'0 BMP',	codeStart:'U+1100',	codeEnd:'U+11FF',	nameCht:'諺文字母',	nameEng:'Hangul Jamo',	description:'諺文' },
    { plane:'0 BMP',	codeStart:'U+1200',	codeEnd:'U+137F',	nameCht:'衣索比亞字母',	nameEng:'Ethiopic',	description:'吉茲字母' },
    { plane:'0 BMP',	codeStart:'U+1380',	codeEnd:'U+139F',	nameCht:'衣索比亞字母補充',	nameEng:'Ethiopic Supplement',	description:'吉茲字母' },
    { plane:'0 BMP',	codeStart:'U+13A0',	codeEnd:'U+13FF',	nameCht:'切羅基文',	nameEng:'Cherokee',	description:'切羅基文' },
    { plane:'0 BMP',	codeStart:'U+1400',	codeEnd:'U+167F',	nameCht:'統一加拿大原住民音節文字',	nameEng:'Unified Canadian Aboriginal Syllabics',	description:'加拿大原住民音節文字' },
    { plane:'0 BMP',	codeStart:'U+1680',	codeEnd:'U+169F',	nameCht:'歐甘字母',	nameEng:'Ogham',	description:'歐甘字母' },
    { plane:'0 BMP',	codeStart:'U+16A0',	codeEnd:'U+16FF',	nameCht:'盧恩字母',	nameEng:'Runic',	description:'盧恩字母（86個）、通用（3個）' },
    { plane:'0 BMP',	codeStart:'U+1700',	codeEnd:'U+171F',	nameCht:'他加祿字母',	nameEng:'Tagalog',	description:'他加祿字母' },
    { plane:'0 BMP',	codeStart:'U+1720',	codeEnd:'U+173F',	nameCht:'哈努諾文',	nameEng:'Hanunoo',	description:'哈努諾字母（21個）、通用（2個）' },
    { plane:'0 BMP',	codeStart:'U+1740',	codeEnd:'U+175F',	nameCht:'布希德字母',	nameEng:'Buhid',	description:'布希德文' },
    { plane:'0 BMP',	codeStart:'U+1760',	codeEnd:'U+177F',	nameCht:'塔格班瓦字母',	nameEng:'Tagbanwa',	description:'塔格班瓦字母' },
    { plane:'0 BMP',	codeStart:'U+1780',	codeEnd:'U+17FF',	nameCht:'高棉文',	nameEng:'Khmer',	description:'高棉文' },
    { plane:'0 BMP',	codeStart:'U+1800',	codeEnd:'U+18AF',	nameCht:'蒙古文',	nameEng:'Mongolian',	description:'蒙古文字母（155個）、通用（3個）' },
    { plane:'0 BMP',	codeStart:'U+18B0',	codeEnd:'U+18FF',	nameCht:'統一加拿大原住民音節文字擴充',	nameEng:'Unified Canadian Aboriginal Syllabics Extended',	description:'加拿大原住民音節文字' },
    { plane:'0 BMP',	codeStart:'U+1900',	codeEnd:'U+194F',	nameCht:'林布文',	nameEng:'Limbu',	description:'林布文' },
    { plane:'0 BMP',	codeStart:'U+1950',	codeEnd:'U+197F',	nameCht:'德宏傣文',	nameEng:'Tai Le',	description:'德宏傣文' },
    { plane:'0 BMP',	codeStart:'U+1980',	codeEnd:'U+19DF',	nameCht:'新傣仂文',	nameEng:'New Tai Lue',	description:'新傣仂文' },
    { plane:'0 BMP',	codeStart:'U+19E0',	codeEnd:'U+19FF',	nameCht:'高棉文符號',	nameEng:'Khmer Symbols',	description:'高棉文' },
    { plane:'0 BMP',	codeStart:'U+1A00',	codeEnd:'U+1A1F',	nameCht:'布吉文',	nameEng:'Buginese',	description:'布吉文' },
    { plane:'0 BMP',	codeStart:'U+1A20',	codeEnd:'U+1AAF',	nameCht:'老傣仂文',	nameEng:'Tai Tham',	description:'老傣仂文' },
    { plane:'0 BMP',	codeStart:'U+1AB0',	codeEnd:'U+1AFF',	nameCht:'組合附加符號擴展',	nameEng:'Combining Diacritical Marks Extended',	description:'繼承' },
    { plane:'0 BMP',	codeStart:'U+1B00',	codeEnd:'U+1B7F',	nameCht:'峇里字母',	nameEng:'Balinese',	description:'峇里字母' },
    { plane:'0 BMP',	codeStart:'U+1B80',	codeEnd:'U+1BBF',	nameCht:'巽他字母',	nameEng:'Sundanese',	description:'巽他字母' },
    { plane:'0 BMP',	codeStart:'U+1BC0',	codeEnd:'U+1BFF',	nameCht:'巴塔克字母',	nameEng:'Batak',	description:'巴塔克字母' },
    { plane:'0 BMP',	codeStart:'U+1C00',	codeEnd:'U+1C4F',	nameCht:'絨巴文',	nameEng:'Lepcha',	description:'絨巴文' },
    { plane:'0 BMP',	codeStart:'U+1C50',	codeEnd:'U+1C7F',	nameCht:'桑塔利文',	nameEng:'Ol Chiki',	description:'桑塔利文' },
    { plane:'0 BMP',	codeStart:'U+1C80',	codeEnd:'U+1C8F',	nameCht:'西里爾字母擴展-C',	nameEng:'Cyrillic Extended-C',	description:'西里爾字母' },
    { plane:'0 BMP',	codeStart:'U+1C90',	codeEnd:'U+1CBF',	nameCht:'喬治亞字母擴展',	nameEng:'Georgian Extended',	description:'喬治亞字母' },
    { plane:'0 BMP',	codeStart:'U+1CC0',	codeEnd:'U+1CCF',	nameCht:'巽他字母補充',	nameEng:'Sundanese Supplement',	description:'巽他字母' },
    { plane:'0 BMP',	codeStart:'U+1CD0',	codeEnd:'U+1CFF',	nameCht:'吠陀擴展',	nameEng:'Vedic Extensions',	description:'通用（16個）、繼承（27個）' },
    { plane:'0 BMP',	codeStart:'U+1D00',	codeEnd:'U+1D7F',	nameCht:'音標擴展',	nameEng:'Phonetic Extensions',	description:'西里爾字母（2個）、希臘字母（15個）、拉丁字母（111個）' },
    { plane:'0 BMP',	codeStart:'U+1D80',	codeEnd:'U+1DBF',	nameCht:'音標擴展補充',	nameEng:'Phonetic Extensions Supplement',	description:'希臘字母（1個）、拉丁字母（63個）' },
    { plane:'0 BMP',	codeStart:'U+1DC0',	codeEnd:'U+1DFF',	nameCht:'組合附加符號補充',	nameEng:'Combining Diacritical Marks Supplement',	description:'繼承' },
    { plane:'0 BMP',	codeStart:'U+1E00',	codeEnd:'U+1EFF',	nameCht:'拉丁字母擴展附加',	nameEng:'Latin Extended Additional',	description:'拉丁' },
    { plane:'0 BMP',	codeStart:'U+1F00',	codeEnd:'U+1FFF',	nameCht:'希臘字母擴展',	nameEng:'Greek Extended',	description:'希臘字母' },
    { plane:'0 BMP',	codeStart:'U+2000',	codeEnd:'U+206F',	nameCht:'一般標點',	nameEng:'General Punctuation',	description:'通用（109個）、繼承（2個）' },
    { plane:'0 BMP',	codeStart:'U+2070',	codeEnd:'U+209F',	nameCht:'上標及下標',	nameEng:'Superscripts and Subscripts',	description:'拉丁（15個）、通用（27個）' },
    { plane:'0 BMP',	codeStart:'U+20A0',	codeEnd:'U+20CF',	nameCht:'貨幣符號',	nameEng:'Currency Symbols',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+20D0',	codeEnd:'U+20FF',	nameCht:'符號用組合附加符號',	nameEng:'Combining Diacritical Marks for Symbols',	description:'繼承' },
    { plane:'0 BMP',	codeStart:'U+2100',	codeEnd:'U+214F',	nameCht:'類字母符號',	nameEng:'Letterlike Symbols',	description:'希臘文（1個）、拉丁（4個）、通用（75個）' },
    { plane:'0 BMP',	codeStart:'U+2150',	codeEnd:'U+218F',	nameCht:'數字形式',	nameEng:'Number Forms',	description:'拉丁（41個）、通用（19個）' },
    { plane:'0 BMP',	codeStart:'U+2190',	codeEnd:'U+21FF',	nameCht:'箭頭',	nameEng:'Arrows',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2200',	codeEnd:'U+22FF',	nameCht:'數學運算子',	nameEng:'Mathematical Operators',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2300',	codeEnd:'U+23FF',	nameCht:'雜項技術符號',	nameEng:'Miscellaneous Technical',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2400',	codeEnd:'U+243F',	nameCht:'控制圖形',	nameEng:'Control Pictures',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2440',	codeEnd:'U+245F',	nameCht:'光學字元識別',	nameEng:'Optical Character Recognition',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2460',	codeEnd:'U+24FF',	nameCht:'圍繞字母數字',	nameEng:'Enclosed Alphanumerics',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2500',	codeEnd:'U+257F',	nameCht:'制表符',	nameEng:'Box Drawing',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2580',	codeEnd:'U+259F',	nameCht:'方塊元素',	nameEng:'Block Elements',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+25A0',	codeEnd:'U+25FF',	nameCht:'幾何圖形',	nameEng:'Geometric Shapes',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2600',	codeEnd:'U+26FF',	nameCht:'雜項符號',	nameEng:'Miscellaneous Symbols',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2700',	codeEnd:'U+27BF',	nameCht:'裝飾符號',	nameEng:'Dingbats',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+27C0',	codeEnd:'U+27EF',	nameCht:'雜項數學符號-A',	nameEng:'Miscellaneous Mathematical Symbols-A',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+27F0',	codeEnd:'U+27FF',	nameCht:'追加箭頭-A',	nameEng:'Supplemental Arrows-A',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2800',	codeEnd:'U+28FF',	nameCht:'點字圖案',	nameEng:'Braille Patterns',	description:'盲文' },
    { plane:'0 BMP',	codeStart:'U+2900',	codeEnd:'U+297F',	nameCht:'追加箭頭-B',	nameEng:'Supplemental Arrows-B',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2980',	codeEnd:'U+29FF',	nameCht:'雜項數學符號-B',	nameEng:'Miscellaneous Mathematical Symbols-B',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2A00',	codeEnd:'U+2AFF',	nameCht:'補充數學運算子',	nameEng:'Supplemental Mathematical Operators',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2B00',	codeEnd:'U+2BFF',	nameCht:'雜項符號和箭頭',	nameEng:'Miscellaneous Symbols and Arrows',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2C00',	codeEnd:'U+2C5F',	nameCht:'格拉哥里字母',	nameEng:'Glagolitic',	description:'格拉哥里字母' },
    { plane:'0 BMP',	codeStart:'U+2C60',	codeEnd:'U+2C7F',	nameCht:'拉丁字母擴展-C',	nameEng:'Latin Extended-C',	description:'拉丁字母' },
    { plane:'0 BMP',	codeStart:'U+2C80',	codeEnd:'U+2CFF',	nameCht:'科普特字母',	nameEng:'Coptic',	description:'科普特字母' },
    { plane:'0 BMP',	codeStart:'U+2D00',	codeEnd:'U+2D2F',	nameCht:'喬治亞字母補充',	nameEng:'Georgian Supplement',	description:'喬治亞字母' },
    { plane:'0 BMP',	codeStart:'U+2D30',	codeEnd:'U+2D7F',	nameCht:'提非納文',	nameEng:'Tifinagh',	description:'提非納文' },
    { plane:'0 BMP',	codeStart:'U+2D80',	codeEnd:'U+2DDF',	nameCht:'衣索比亞字母擴充',	nameEng:'Ethiopic Extended',	description:'吉茲字母' },
    { plane:'0 BMP',	codeStart:'U+2DE0',	codeEnd:'U+2DFF',	nameCht:'西里爾字母擴展-A',	nameEng:'Cyrillic Extended-A',	description:'西里爾字母' },
    { plane:'0 BMP',	codeStart:'U+2E00',	codeEnd:'U+2E7F',	nameCht:'補充標點',	nameEng:'Supplemental Punctuation',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+2E80',	codeEnd:'U+2EFF',	nameCht:'中日韓漢字部首補充',	nameEng:'CJK Radicals Supplement',	description:'漢字' },
    { plane:'0 BMP',	codeStart:'U+2F00',	codeEnd:'U+2FDF',	nameCht:'康熙部首',	nameEng:'Kangxi Radicals',	description:'漢字' },
    { plane:'0 BMP',	codeStart:'U+2FF0',	codeEnd:'U+2FFF',	nameCht:'表意文字描述字元',	nameEng:'Ideographic Description Characters',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+3000',	codeEnd:'U+303F',	nameCht:'中日韓符號和標點',	nameEng:'CJK Symbols and Punctuation',	description:'漢字（15個）、諺文（2個）、通用（43個）、繼承（4個）' },
    { plane:'0 BMP',	codeStart:'U+3040',	codeEnd:'U+309F',	nameCht:'平假名',	nameEng:'Hiragana',	description:'平假名（89個）、通用（2個）、繼承（2個）' },
    { plane:'0 BMP',	codeStart:'U+30A0',	codeEnd:'U+30FF',	nameCht:'片假名',	nameEng:'Katakana',	description:'片假名（93個）、通用（3個）' },
    { plane:'0 BMP',	codeStart:'U+3100',	codeEnd:'U+312F',	nameCht:'注音符號',	nameEng:'Bopomofo',	description:'注音符號' },
    { plane:'0 BMP',	codeStart:'U+3130',	codeEnd:'U+318F',	nameCht:'諺文相容字母',	nameEng:'Hangul Compatibility Jamo',	description:'諺文' },
    { plane:'0 BMP',	codeStart:'U+3190',	codeEnd:'U+319F',	nameCht:'漢文訓讀符號',	nameEng:'Kanbun',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+31A0',	codeEnd:'U+31BF',	nameCht:'注音符號擴展',	nameEng:'Bopomofo Extended',	description:'注音符號' },
    { plane:'0 BMP',	codeStart:'U+31C0',	codeEnd:'U+31EF',	nameCht:'中日韓筆畫',	nameEng:'CJK Strokes',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+31F0',	codeEnd:'U+31FF',	nameCht:'片假名語音擴展',	nameEng:'Katakana Phonetic Extensions',	description:'片假名' },
    { plane:'0 BMP',	codeStart:'U+3200',	codeEnd:'U+32FF',	nameCht:'中日韓圍繞字元及月份',	nameEng:'Enclosed CJK Letters and Months',	description:'諺文（62個）、片假名（47個）、通用（146個）' },
    { plane:'0 BMP',	codeStart:'U+3300',	codeEnd:'U+33FF',	nameCht:'中日韓相容字元',	nameEng:'CJK Compatibility',	description:'片假名（88個）、通用（168個）' },
    { plane:'0 BMP',	codeStart:'U+3400',	codeEnd:'U+4DBF',	nameCht:'中日韓統一表意文字擴充區A',	nameEng:'CJK Unified Ideographs Extension A',	description:'漢字' },
    { plane:'0 BMP',	codeStart:'U+4DC0',	codeEnd:'U+4DFF',	nameCht:'易經六十四卦符號',	nameEng:'Yijing Hexagram Symbols',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+4E00',	codeEnd:'U+9FFF',	nameCht:'中日韓統一表意文字 (基本區)',	nameEng:'CJK Unified Ideographs',	description:'漢字' },
    { plane:'0 BMP',	codeStart:'U+A000',	codeEnd:'U+A48F',	nameCht:'彝文音節',	nameEng:'Yi Syllables',	description:'彝文' },
    { plane:'0 BMP',	codeStart:'U+A490',	codeEnd:'U+A4CF',	nameCht:'彝文部首',	nameEng:'Yi Radicals',	description:'彝文' },
    { plane:'0 BMP',	codeStart:'U+A4D0',	codeEnd:'U+A4FF',	nameCht:'傈僳文',	nameEng:'Lisu',	description:'老傈僳文' },
    { plane:'0 BMP',	codeStart:'U+A500',	codeEnd:'U+A63F',	nameCht:'瓦伊文',	nameEng:'Vai',	description:'瓦伊文' },
    { plane:'0 BMP',	codeStart:'U+A640',	codeEnd:'U+A69F',	nameCht:'西里爾字母擴展-B',	nameEng:'Cyrillic Extended-B',	description:'西里爾字母' },
    { plane:'0 BMP',	codeStart:'U+A6A0',	codeEnd:'U+A6FF',	nameCht:'巴姆穆文字',	nameEng:'Bamum',	description:'巴姆穆文字' },
    { plane:'0 BMP',	codeStart:'U+A700',	codeEnd:'U+A71F',	nameCht:'聲調修飾符號',	nameEng:'Modifier Tone Letters',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+A720',	codeEnd:'U+A7FF',	nameCht:'拉丁字母擴展-D',	nameEng:'Latin Extended-D',	description:'拉丁（188個）、通用（5個）' },
    { plane:'0 BMP',	codeStart:'U+A800',	codeEnd:'U+A82F',	nameCht:'錫爾赫特文',	nameEng:'Syloti Nagri',	description:'錫爾赫特文' },
    { plane:'0 BMP',	codeStart:'U+A830',	codeEnd:'U+A83F',	nameCht:'通用印度數字形式',	nameEng:'Common Indic Number Forms',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+A840',	codeEnd:'U+A87F',	nameCht:'八思巴文',	nameEng:'Phags-pa',	description:'八思巴字' },
    { plane:'0 BMP',	codeStart:'U+A880',	codeEnd:'U+A8DF',	nameCht:'條拉什特拉文',	nameEng:'Saurashtra',	description:'條拉什特拉文' },
    { plane:'0 BMP',	codeStart:'U+A8E0',	codeEnd:'U+A8FF',	nameCht:'天城文擴展',	nameEng:'Devanagari Extended',	description:'天城文' },
    { plane:'0 BMP',	codeStart:'U+A900',	codeEnd:'U+A92F',	nameCht:'克耶字母',	nameEng:'Kayah Li',	description:'克耶字母（47個）、通用（1個）' },
    { plane:'0 BMP',	codeStart:'U+A930',	codeEnd:'U+A95F',	nameCht:'勒姜字母',	nameEng:'Rejang',	description:'勒姜字母' },
    { plane:'0 BMP',	codeStart:'U+A960',	codeEnd:'U+A97F',	nameCht:'諺文字母擴展-A',	nameEng:'Hangul Jamo Extended-A',	description:'諺文' },
    { plane:'0 BMP',	codeStart:'U+A980',	codeEnd:'U+A9DF',	nameCht:'爪哇字母',	nameEng:'Javanese',	description:'爪哇字母（90個）、通用（1個）' },
    { plane:'0 BMP',	codeStart:'U+A9E0',	codeEnd:'U+A9FF',	nameCht:'緬甸文擴展-B',	nameEng:'Myanmar Extended-B',	description:'緬甸文' },
    { plane:'0 BMP',	codeStart:'U+AA00',	codeEnd:'U+AA5F',	nameCht:'占文',	nameEng:'Cham',	description:'占文' },
    { plane:'0 BMP',	codeStart:'U+AA60',	codeEnd:'U+AA7F',	nameCht:'緬甸文擴展-A',	nameEng:'Myanmar Extended-A',	description:'緬文' },
    { plane:'0 BMP',	codeStart:'U+AA80',	codeEnd:'U+AADF',	nameCht:'傣越文',	nameEng:'Tai Viet',	description:'傣越文' },
    { plane:'0 BMP',	codeStart:'U+AAE0',	codeEnd:'U+AAFF',	nameCht:'梅泰文擴充',	nameEng:'Meetei Mayek Extensions',	description:'曼尼普爾文' },
    { plane:'0 BMP',	codeStart:'U+AB00',	codeEnd:'U+AB2F',	nameCht:'衣索比亞字母擴充-A',	nameEng:'Ethiopic Extended-A',	description:'吉茲字母' },
    { plane:'0 BMP',	codeStart:'U+AB30',	codeEnd:'U+AB6F',	nameCht:'拉丁字母擴展-E',	nameEng:'Latin Extended-E',	description:'拉丁（56個）、希臘語（1個）、通用（3個）' },
    { plane:'0 BMP',	codeStart:'U+AB70',	codeEnd:'U+ABBF',	nameCht:'切羅基文補充',	nameEng:'Cherokee Supplement',	description:'切羅基文' },
    { plane:'0 BMP',	codeStart:'U+ABC0',	codeEnd:'U+ABFF',	nameCht:'梅泰文',	nameEng:'Meetei Mayek',	description:'梅泰文' },
    { plane:'0 BMP',	codeStart:'U+AC00',	codeEnd:'U+D7AF',	nameCht:'諺文音節',	nameEng:'Hangul Syllables',	description:'諺文' },
    { plane:'0 BMP',	codeStart:'U+D7B0',	codeEnd:'U+D7FF',	nameCht:'諺文字母擴展-B',	nameEng:'Hangul Jamo Extended-B',	description:'諺文' },
    { plane:'0 BMP',	codeStart:'U+D800',	codeEnd:'U+DB7F',	nameCht:'高半代用區',	nameEng:'High Surrogates',	description:'未知' },
    { plane:'0 BMP',	codeStart:'U+DB80',	codeEnd:'U+DBFF',	nameCht:'高半私人代用區',	nameEng:'High Private Use Surrogates',	description:'未知' },
    { plane:'0 BMP',	codeStart:'U+DC00',	codeEnd:'U+DFFF',	nameCht:'低半代用區',	nameEng:'Low Surrogates',	description:'未知' },
    { plane:'0 BMP',	codeStart:'U+E000',	codeEnd:'U+F8FF',	nameCht:'私用區',	nameEng:'Private Use Area',	description:'未知' },
    { plane:'0 BMP',	codeStart:'U+F900',	codeEnd:'U+FAFF',	nameCht:'中日韓相容表意文字',	nameEng:'CJK Compatibility Ideographs',	description:'漢字' },
    { plane:'0 BMP',	codeStart:'U+FB00',	codeEnd:'U+FB4F',	nameCht:'字母表達形式',	nameEng:'Alphabetic Presentation Forms',	description:'亞美尼亞文（5個）、希伯來文（46個）、拉丁（7個）' },
    { plane:'0 BMP',	codeStart:'U+FB50',	codeEnd:'U+FDFF',	nameCht:'阿拉伯字母表達形式-A',	nameEng:'Arabic Presentation Forms-A',	description:'阿拉伯字母（629個）、通用（2個）' },
    { plane:'0 BMP',	codeStart:'U+FE00',	codeEnd:'U+FE0F',	nameCht:'變體選擇符',	nameEng:'Variation Selectors',	description:'繼承' },
    { plane:'0 BMP',	codeStart:'U+FE10',	codeEnd:'U+FE1F',	nameCht:'豎排形式',	nameEng:'Vertical Forms',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+FE20',	codeEnd:'U+FE2F',	nameCht:'組合用半符號',	nameEng:'Combining Half Marks',	description:'西里爾字母（2個）、繼承（14個）' },
    { plane:'0 BMP',	codeStart:'U+FE30',	codeEnd:'U+FE4F',	nameCht:'中日韓相容形式',	nameEng:'CJK Compatibility Forms',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+FE50',	codeEnd:'U+FE6F',	nameCht:'小寫變體形式',	nameEng:'Small Form Variants',	description:'通用' },
    { plane:'0 BMP',	codeStart:'U+FE70',	codeEnd:'U+FEFF',	nameCht:'阿拉伯字母表達形式-B',	nameEng:'Arabic Presentation Forms-B',	description:'阿拉伯字母（140個）、通用（1個）' },
    { plane:'0 BMP',	codeStart:'U+FF00',	codeEnd:'U+FFEF',	nameCht:'半形及全形字元',	nameEng:'Halfwidth and Fullwidth Forms',	description:'諺文（52個）、片假名（55個）、拉丁（52個）、通用（66個）' },
    { plane:'0 BMP',	codeStart:'U+FFF0',	codeEnd:'U+FFFF',	nameCht:'特殊',	nameEng:'Specials',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+10000',	codeEnd:'U+1007F',	nameCht:'線形文字B音節文字',	nameEng:'Linear B Syllabary',	description:'線形文字B' },
    { plane:'1 SMP',	codeStart:'U+10080',	codeEnd:'U+100FF',	nameCht:'線形文字B表意文字',	nameEng:'Linear B Ideograms',	description:'線形文字B' },
    { plane:'1 SMP',	codeStart:'U+10100',	codeEnd:'U+1013F',	nameCht:'愛琴海數字',	nameEng:'Aegean Numbers',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+10140',	codeEnd:'U+1018F',	nameCht:'古希臘數字',	nameEng:'Ancient Greek Numbers',	description:'希臘文' },
    { plane:'1 SMP',	codeStart:'U+10190',	codeEnd:'U+101CF',	nameCht:'古代符號',	nameEng:'Ancient Symbols',	description:'希臘文（1個）、通用（13個）' },
    { plane:'1 SMP',	codeStart:'U+101D0',	codeEnd:'U+101FF',	nameCht:'斐斯托斯圓盤',	nameEng:'Phaistos Disc',	description:'通用（45個）、繼承（1個）' },
    { plane:'1 SMP',	codeStart:'U+10280',	codeEnd:'U+1029F',	nameCht:'呂基亞字母',	nameEng:'Lycian',	description:'呂基亞字母' },
    { plane:'1 SMP',	codeStart:'U+102A0',	codeEnd:'U+102DF',	nameCht:'卡里亞字母',	nameEng:'Carian',	description:'卡利亞字母' },
    { plane:'1 SMP',	codeStart:'U+102E0',	codeEnd:'U+102FF',	nameCht:'科普特閏餘數字',	nameEng:'Coptic Epact Numbers',	description:'通用（27個）、繼承（1個）' },
    { plane:'1 SMP',	codeStart:'U+10300',	codeEnd:'U+1032F',	nameCht:'古義大利字母',	nameEng:'Old Italic',	description:'古義大利字母' },
    { plane:'1 SMP',	codeStart:'U+10330',	codeEnd:'U+1034F',	nameCht:'哥特字母',	nameEng:'Gothic',	description:'哥特字母' },
    { plane:'1 SMP',	codeStart:'U+10350',	codeEnd:'U+1037F',	nameCht:'古彼爾姆文',	nameEng:'Old Permic',	description:'古彼爾姆文' },
    { plane:'1 SMP',	codeStart:'U+10380',	codeEnd:'U+1039F',	nameCht:'烏加里特字母',	nameEng:'Ugaritic',	description:'烏加里特字母' },
    { plane:'1 SMP',	codeStart:'U+103A0',	codeEnd:'U+103DF',	nameCht:'古波斯楔形文字',	nameEng:'Old Persian',	description:'古波斯楔形文字' },
    { plane:'1 SMP',	codeStart:'U+10400',	codeEnd:'U+1044F',	nameCht:'德瑟雷特字母',	nameEng:'Deseret',	description:'德瑟雷特字母' },
    { plane:'1 SMP',	codeStart:'U+10450',	codeEnd:'U+1047F',	nameCht:'蕭伯納字母',	nameEng:'Shavian',	description:'蕭伯納字母' },
    { plane:'1 SMP',	codeStart:'U+10480',	codeEnd:'U+104AF',	nameCht:'奧斯曼亞字母',	nameEng:'Osmanya',	description:'奧斯曼亞字母' },
    { plane:'1 SMP',	codeStart:'U+104B0',	codeEnd:'U+104FF',	nameCht:'歐塞奇字母',	nameEng:'Osage',	description:'歐塞奇字母' },
    { plane:'1 SMP',	codeStart:'U+10500',	codeEnd:'U+1052F',	nameCht:'愛爾巴桑字母',	nameEng:'Elbasan',	description:'愛爾巴桑字母' },
    { plane:'1 SMP',	codeStart:'U+10530',	codeEnd:'U+1056F',	nameCht:'高加條阿爾巴尼亞字母',	nameEng:'Caucasian Albanian',	description:'高加條阿爾巴尼亞文' },
    { plane:'1 SMP',	codeStart:'U+10570',	codeEnd:'U+105BF',	nameCht:'維斯庫奇文',	nameEng:'Vithkuqi',	description:'維斯庫奇文' },
    { plane:'1 SMP',	codeStart:'U+10600',	codeEnd:'U+1077F',	nameCht:'線形文字A',	nameEng:'Linear A',	description:'線形文字A' },
    { plane:'1 SMP',	codeStart:'U+10780',	codeEnd:'U+107BF',	nameCht:'拉丁字母擴展-F',	nameEng:'Latin Extended-F',	description:'拉丁字母' },
    { plane:'1 SMP',	codeStart:'U+10800',	codeEnd:'U+1083F',	nameCht:'賽普勒斯音節文字',	nameEng:'Cypriot Syllabary',	description:'賽普勒斯音節文字' },
    { plane:'1 SMP',	codeStart:'U+10840',	codeEnd:'U+1085F',	nameCht:'帝國亞拉姆文',	nameEng:'Imperial Aramaic',	description:'帝國亞拉姆文字' },
    { plane:'1 SMP',	codeStart:'U+10860',	codeEnd:'U+1087F',	nameCht:'帕爾邁拉字母',	nameEng:'Palmyrene',	description:'帕爾邁拉字母' },
    { plane:'1 SMP',	codeStart:'U+10880',	codeEnd:'U+108AF',	nameCht:'納巴泰字母',	nameEng:'Nabataean',	description:'納巴泰字母' },
    { plane:'1 SMP',	codeStart:'U+108E0',	codeEnd:'U+108FF',	nameCht:'哈特拉文',	nameEng:'Hatran',	description:'哈特拉文' },
    { plane:'1 SMP',	codeStart:'U+10900',	codeEnd:'U+1091F',	nameCht:'腓尼基字母',	nameEng:'Phoenician',	description:'腓尼基字母' },
    { plane:'1 SMP',	codeStart:'U+10920',	codeEnd:'U+1093F',	nameCht:'呂底亞字母',	nameEng:'Lydian',	description:'呂底亞字母' },
    { plane:'1 SMP',	codeStart:'U+10980',	codeEnd:'U+1099F',	nameCht:'麥羅埃文聖書體',	nameEng:'Meroitic Hieroglyphs',	description:'麥羅埃文聖書體' },
    { plane:'1 SMP',	codeStart:'U+109A0',	codeEnd:'U+109FF',	nameCht:'麥羅埃文草書體',	nameEng:'Meroitic Cursive',	description:'麥羅埃文草書體' },
    { plane:'1 SMP',	codeStart:'U+10A00',	codeEnd:'U+10A5F',	nameCht:'佉盧文',	nameEng:'Kharoshthi',	description:'佉盧文' },
    { plane:'1 SMP',	codeStart:'U+10A60',	codeEnd:'U+10A7F',	nameCht:'古南阿拉伯字母',	nameEng:'Old South Arabian',	description:'古南阿拉伯字母' },
    { plane:'1 SMP',	codeStart:'U+10A80',	codeEnd:'U+10A9F',	nameCht:'古北阿拉伯字母',	nameEng:'Old North Arabian',	description:'古北阿拉伯字母' },
    { plane:'1 SMP',	codeStart:'U+10AC0',	codeEnd:'U+10AFF',	nameCht:'摩尼字母',	nameEng:'Manichaean',	description:'摩尼字母' },
    { plane:'1 SMP',	codeStart:'U+10B00',	codeEnd:'U+10B3F',	nameCht:'阿維斯陀字母',	nameEng:'Avestan',	description:'阿維斯陀字母' },
    { plane:'1 SMP',	codeStart:'U+10B40',	codeEnd:'U+10B5F',	nameCht:'碑刻帕提亞文',	nameEng:'Inscriptional Parthian',	description:'碑刻帕提亞文' },
    { plane:'1 SMP',	codeStart:'U+10B60',	codeEnd:'U+10B7F',	nameCht:'碑刻巴列維文',	nameEng:'Inscriptional Pahlavi',	description:'碑刻巴列維文' },
    { plane:'1 SMP',	codeStart:'U+10B80',	codeEnd:'U+10BAF',	nameCht:'詩篇巴列維文',	nameEng:'Psalter Pahlavi',	description:'詩篇巴列維文' },
    { plane:'1 SMP',	codeStart:'U+10C00',	codeEnd:'U+10C4F',	nameCht:'古突厥文',	nameEng:'Old Turkic',	description:'古突厥文' },
    { plane:'1 SMP',	codeStart:'U+10C80',	codeEnd:'U+10CFF',	nameCht:'古匈牙利字母',	nameEng:'Old Hungarian',	description:'古匈牙利字母' },
    { plane:'1 SMP',	codeStart:'U+10D00',	codeEnd:'U+10D3F',	nameCht:'哈乃斐羅興亞文字',	nameEng:'Hanifi Rohingya',	description:'哈乃斐羅興亞文字' },
    { plane:'1 SMP',	codeStart:'U+10E60',	codeEnd:'U+10E7F',	nameCht:'盧米文數字',	nameEng:'Rumi Numeral Symbols',	description:'阿拉伯文' },
    { plane:'1 SMP',	codeStart:'U+10E80',	codeEnd:'U+10EBF',	nameCht:'雅茲迪文',	nameEng:'Yezidi',	description:'雅茲迪文' },
    { plane:'1 SMP',	codeStart:'U+10EC0',	codeEnd:'U+10EFF',	nameCht:'阿拉伯字母擴展-C',	nameEng:'Arabic Extended-C',	description:'阿拉伯字母' },
    { plane:'1 SMP',	codeStart:'U+10F00',	codeEnd:'U+10F2F',	nameCht:'古粟特字母',	nameEng:'Old Sogdian',	description:'古粟特字母' },
    { plane:'1 SMP',	codeStart:'U+10F30',	codeEnd:'U+10F6F',	nameCht:'粟特字母',	nameEng:'Sogdian',	description:'粟特字母' },
    { plane:'1 SMP',	codeStart:'U+10F70',	codeEnd:'U+10FAF',	nameCht:'回鶻字母',	nameEng:'Old Uyghur',	description:'回鶻字母' },
    { plane:'1 SMP',	codeStart:'U+10FB0',	codeEnd:'U+10FDF',	nameCht:'花剌子模字母',	nameEng:'Chorasmian',	description:'花剌子模字母' },
    { plane:'1 SMP',	codeStart:'U+10FE0',	codeEnd:'U+10FFF',	nameCht:'埃利邁文',	nameEng:'Elymaic',	description:'埃利邁文' },
    { plane:'1 SMP',	codeStart:'U+11000',	codeEnd:'U+1107F',	nameCht:'婆羅米文',	nameEng:'Brahmi',	description:'婆羅米文' },
    { plane:'1 SMP',	codeStart:'U+11080',	codeEnd:'U+110CF',	nameCht:'凱提文',	nameEng:'Kaithi',	description:'凱提文' },
    { plane:'1 SMP',	codeStart:'U+110D0',	codeEnd:'U+110FF',	nameCht:'條拉僧平文字',	nameEng:'Sora Sompeng',	description:'條拉僧平文字' },
    { plane:'1 SMP',	codeStart:'U+11100',	codeEnd:'U+1114F',	nameCht:'查克馬文',	nameEng:'Chakma',	description:'查克馬文' },
    { plane:'1 SMP',	codeStart:'U+11150',	codeEnd:'U+1117F',	nameCht:'馬哈佳尼文',	nameEng:'Mahajani',	description:'馬哈佳尼文' },
    { plane:'1 SMP',	codeStart:'U+11180',	codeEnd:'U+111DF',	nameCht:'夏拉達文',	nameEng:'Sharada',	description:'夏拉達文' },
    { plane:'1 SMP',	codeStart:'U+111E0',	codeEnd:'U+111FF',	nameCht:'古僧伽羅文數字',	nameEng:'Sinhala Archaic Numbers',	description:'古僧伽羅文數字' },
    { plane:'1 SMP',	codeStart:'U+11200',	codeEnd:'U+1124F',	nameCht:'可吉文',	nameEng:'Khojki',	description:'可吉文' },
    { plane:'1 SMP',	codeStart:'U+11280',	codeEnd:'U+112AF',	nameCht:'穆爾塔尼文',	nameEng:'Multani',	description:'穆爾塔尼文' },
    { plane:'1 SMP',	codeStart:'U+112B0',	codeEnd:'U+112FF',	nameCht:'庫達瓦迪文',	nameEng:'Khudawadi',	description:'庫達瓦迪文' },
    { plane:'1 SMP',	codeStart:'U+11300',	codeEnd:'U+1137F',	nameCht:'古蘭塔文',	nameEng:'Grantha',	description:'古蘭塔文' },
    { plane:'1 SMP',	codeStart:'U+11400',	codeEnd:'U+1147F',	nameCht:'紐瓦字母',	nameEng:'Newa',	description:'紐瓦字母' },
    { plane:'1 SMP',	codeStart:'U+11480',	codeEnd:'U+114DF',	nameCht:'底羅僕多文',	nameEng:'Tirhuta',	description:'底羅仆多文' },
    { plane:'1 SMP',	codeStart:'U+11580',	codeEnd:'U+115FF',	nameCht:'悉曇文字',	nameEng:'Siddham',	description:'悉曇文字' },
    { plane:'1 SMP',	codeStart:'U+11600',	codeEnd:'U+1165F',	nameCht:'莫迪文',	nameEng:'Modi',	description:'莫迪文' },
    { plane:'1 SMP',	codeStart:'U+11660',	codeEnd:'U+1167F',	nameCht:'蒙古文補充',	nameEng:'Mongolian Supplement',	description:'蒙古文' },
    { plane:'1 SMP',	codeStart:'U+11680',	codeEnd:'U+116CF',	nameCht:'塔克里文',	nameEng:'Takri',	description:'塔克里文' },
    { plane:'1 SMP',	codeStart:'U+11700',	codeEnd:'U+1174F',	nameCht:'阿洪姆文',	nameEng:'Ahom',	description:'阿洪姆文' },
    { plane:'1 SMP',	codeStart:'U+11800',	codeEnd:'U+1184F',	nameCht:'多格拉文',	nameEng:'Dogra',	description:'多格拉文' },
    { plane:'1 SMP',	codeStart:'U+118A0',	codeEnd:'U+118FF',	nameCht:'瓦蘭齊地文',	nameEng:'Warang Citi',	description:'瓦蘭齊地文' },
    { plane:'1 SMP',	codeStart:'U+11900',	codeEnd:'U+1195F',	nameCht:'島嶼字母',	nameEng:'Dhives Akuru (Dives Akuru)',	description:'島嶼字母' },
    { plane:'1 SMP',	codeStart:'U+119A0',	codeEnd:'U+119FF',	nameCht:'南迪城文',	nameEng:'Nandinagari',	description:'南迪城文' },
    { plane:'1 SMP',	codeStart:'U+11A00',	codeEnd:'U+11A4F',	nameCht:'札那巴札爾方形字母',	nameEng:'Zanabazar Square',	description:'札那巴札爾方形字母' },
    { plane:'1 SMP',	codeStart:'U+11A50',	codeEnd:'U+11AAF',	nameCht:'條永布文字',	nameEng:'Soyombo',	description:'條永布文字' },
    { plane:'1 SMP',	codeStart:'U+11AB0',	codeEnd:'U+11ABF',	nameCht:'加拿大原住民音節文字擴展-A',	nameEng:'Unified Canadian Aboriginal Syllabics Extended-A',	description:'加拿大原住民音節文字' },
    { plane:'1 SMP',	codeStart:'U+11AC0',	codeEnd:'U+11AFF',	nameCht:'包欽豪文',	nameEng:'Pau Cin Hau',	description:'包欽豪文' },
    { plane:'1 SMP',	codeStart:'U+11B00',	codeEnd:'U+11B5F',	nameCht:'天城文擴展-A',	nameEng:'Devanagari Extended-A',	description:'天城文' },
    { plane:'1 SMP',	codeStart:'U+11C00',	codeEnd:'U+11C6F',	nameCht:'拜克舒基文',	nameEng:'Bhaiksuki',	description:'拜克舒基文' },
    { plane:'1 SMP',	codeStart:'U+11C70',	codeEnd:'U+11CBF',	nameCht:'瑪欽文',	nameEng:'Marchen',	description:'瑪欽文' },
    { plane:'1 SMP',	codeStart:'U+11D00',	codeEnd:'U+11D5F',	nameCht:'馬薩拉姆貢德文字',	nameEng:'Masaram Gondi',	description:'馬薩拉姆貢德文字' },
    { plane:'1 SMP',	codeStart:'U+11D60',	codeEnd:'U+11DAF',	nameCht:'貢賈拉貢德文字',	nameEng:'Gunjala Gondi',	description:'貢賈拉貢德文字' },
    { plane:'1 SMP',	codeStart:'U+11EE0',	codeEnd:'U+11EFF',	nameCht:'望加錫文',	nameEng:'Makasar',	description:'望加錫文' },
    { plane:'1 SMP',	codeStart:'U+11F00',	codeEnd:'U+11F5F',	nameCht:'卡維文',	nameEng:'Kawi',	description:'卡維文' },
    { plane:'1 SMP',	codeStart:'U+11FB0',	codeEnd:'U+11FBF',	nameCht:'老傈僳文補充',	nameEng:'Lisu Supplement',	description:'老傈僳文' },
    { plane:'1 SMP',	codeStart:'U+11FC0',	codeEnd:'U+11FFF',	nameCht:'泰米爾文補充',	nameEng:'Tamil Supplement',	description:'泰米爾文' },
    { plane:'1 SMP',	codeStart:'U+12000',	codeEnd:'U+123FF',	nameCht:'楔形文字',	nameEng:'Cuneiform',	description:'楔形文字' },
    { plane:'1 SMP',	codeStart:'U+12400',	codeEnd:'U+1247F',	nameCht:'楔形文字數字和標點符號',	nameEng:'Cuneiform Numbers and Punctuation',	description:'楔形文字' },
    { plane:'1 SMP',	codeStart:'U+12480',	codeEnd:'U+1254F',	nameCht:'早期王朝楔形文字',	nameEng:'Early Dynastic Cuneiform',	description:'楔形文字' },
    { plane:'1 SMP',	codeStart:'U+12F90',	codeEnd:'U+12FFF',	nameCht:'賽普勒斯-米諾斯文字',	nameEng:'Cypro-Minoan',	description:'賽普勒斯-米諾斯文字' },
    { plane:'1 SMP',	codeStart:'U+13000',	codeEnd:'U+1342F',	nameCht:'埃及聖書體',	nameEng:'Egyptian Hieroglyphs',	description:'埃及聖書體' },
    { plane:'1 SMP',	codeStart:'U+13430',	codeEnd:'U+1345F',	nameCht:'埃及聖書體格式控制',	nameEng:'Egyptian Hieroglyph Format Controls',	description:'埃及聖書體' },
    { plane:'1 SMP',	codeStart:'U+14400',	codeEnd:'U+1467F',	nameCht:'安納托利亞象形文字',	nameEng:'Anatolian Hieroglyphs',	description:'安納托利亞象形文字' },
    { plane:'1 SMP',	codeStart:'U+16800',	codeEnd:'U+16A3F',	nameCht:'巴姆穆文字補充',	nameEng:'Bamum Supplement',	description:'巴姆穆文字' },
    { plane:'1 SMP',	codeStart:'U+16A40',	codeEnd:'U+16A6F',	nameCht:'默祿文',	nameEng:'Mro',	description:'默祿文' },
    { plane:'1 SMP',	codeStart:'U+16A70',	codeEnd:'U+16ACF',	nameCht:'唐薩文',	nameEng:'Tangsa',	description:'唐薩文' },
    { plane:'1 SMP',	codeStart:'U+16AD0',	codeEnd:'U+16AFF',	nameCht:'巴薩文',	nameEng:'Bassa Vah',	description:'巴薩文' },
    { plane:'1 SMP',	codeStart:'U+16B00',	codeEnd:'U+16B8F',	nameCht:'救世苗文',	nameEng:'Pahawh Hmong',	description:'救世苗文' },
    { plane:'1 SMP',	codeStart:'U+16E40',	codeEnd:'U+16E9F',	nameCht:'梅德法伊德林文',	nameEng:'Medefaidrin',	description:'梅德法伊德林文' },
    { plane:'1 SMP',	codeStart:'U+16F00',	codeEnd:'U+16F9F',	nameCht:'柏格理苗文',	nameEng:'Miao',	description:'柏格理苗文' },
    { plane:'1 SMP',	codeStart:'U+16FE0',	codeEnd:'U+16FFF',	nameCht:'表意符號和標點符號',	nameEng:'Ideographic Symbols and Punctuation',	description:'漢字（2個）、契丹小字（1個）、女書（1個）、西夏文（1個）、通用（2個）' },
    { plane:'1 SMP',	codeStart:'U+17000',	codeEnd:'U+187FF',	nameCht:'西夏文',	nameEng:'Tangut',	description:'西夏文' },
    { plane:'1 SMP',	codeStart:'U+18800',	codeEnd:'U+18AFF',	nameCht:'西夏文部件',	nameEng:'Tangut Components',	description:'西夏文' },
    { plane:'1 SMP',	codeStart:'U+18B00',	codeEnd:'U+18CFF',	nameCht:'契丹小字',	nameEng:'Khitan Small Script',	description:'契丹小字' },
    { plane:'1 SMP',	codeStart:'U+18D00',	codeEnd:'U+18D7F',	nameCht:'西夏文補充',	nameEng:'Tangut Supplement',	description:'西夏文' },
    { plane:'1 SMP',	codeStart:'U+1AFF0',	codeEnd:'U+1AFFF',	nameCht:'假名擴展-B',	nameEng:'Kana Extended-B',	description:'片假名' },
    { plane:'1 SMP',	codeStart:'U+1B000',	codeEnd:'U+1B0FF',	nameCht:'假名補充',	nameEng:'Kana Supplement',	description:'平假名（255個）、片假名（1個）' },
    { plane:'1 SMP',	codeStart:'U+1B100',	codeEnd:'U+1B12F',	nameCht:'假名擴展-A',	nameEng:'Kana Extended-A',	description:'平假名（32個）、片假名（3個）' },
    { plane:'1 SMP',	codeStart:'U+1B130',	codeEnd:'U+1B16F',	nameCht:'小型假名擴充',	nameEng:'Small Kana Extension',	description:'平假名 (4個)、片假名 (5個)' },
    { plane:'1 SMP',	codeStart:'U+1B170',	codeEnd:'U+1B2FF',	nameCht:'女書',	nameEng:'Nushu',	description:'女書' },
    { plane:'1 SMP',	codeStart:'U+1BC00',	codeEnd:'U+1BC9F',	nameCht:'杜普雷速記',	nameEng:'Duployan',	description:'杜普雷速記' },
    { plane:'1 SMP',	codeStart:'U+1BCA0',	codeEnd:'U+1BCAF',	nameCht:'速記格式控制符',	nameEng:'Shorthand Format Controls',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1CF00',	codeEnd:'U+1CFCF',	nameCht:'贊玫尼聖歌音樂符號',	nameEng:'Znamenny Musical Notation',	description:'贊玫尼聖歌音樂符號' },
    { plane:'1 SMP',	codeStart:'U+1D000',	codeEnd:'U+1D0FF',	nameCht:'拜占庭音樂符號',	nameEng:'Byzantine Musical Symbols',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1D100',	codeEnd:'U+1D1FF',	nameCht:'音樂符號',	nameEng:'Musical Symbols',	description:'通用（211個）、繼承（22個）' },
    { plane:'1 SMP',	codeStart:'U+1D200',	codeEnd:'U+1D24F',	nameCht:'古希臘音樂記號',	nameEng:'Ancient Greek Musical Notation',	description:'希臘語' },
    { plane:'1 SMP',	codeStart:'U+1D2C0',	codeEnd:'U+1D2DF',	nameCht:'卡克托維克數字',	nameEng:'Kaktovik Numerals',	description:'因努伊特數字' },
    { plane:'1 SMP',	codeStart:'U+1D2E0',	codeEnd:'U+1D2FF',	nameCht:'瑪雅數字',	nameEng:'Mayan Numerals',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1D300',	codeEnd:'U+1D35F',	nameCht:'太玄經符號',	nameEng:'Tai Xuan Jing Symbols',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1D360',	codeEnd:'U+1D37F',	nameCht:'算籌',	nameEng:'Counting Rod Numerals',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1D400',	codeEnd:'U+1D7FF',	nameCht:'字母和數字符號',	nameEng:'Mathematical Alphanumeric Symbols',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1D800',	codeEnd:'U+1DAAF',	nameCht:'薩頓書寫符號',	nameEng:'Sutton SignWriting',	description:'薩頓書寫符號' },
    { plane:'1 SMP',	codeStart:'U+1DF00',	codeEnd:'U+1DFFF',	nameCht:'拉丁字母擴展-G',	nameEng:'Latin Extended-G',	description:'拉丁字母' },
    { plane:'1 SMP',	codeStart:'U+1E000',	codeEnd:'U+1E02F',	nameCht:'格拉哥里字母補充',	nameEng:'Glagolitic Supplement',	description:'格拉哥里字母' },
    { plane:'1 SMP',	codeStart:'U+1E030',	codeEnd:'U+1E08F',	nameCht:'西里爾字母擴展-D',	nameEng:'Cyrillic Extended-D',	description:'西里爾字母' },
    { plane:'1 SMP',	codeStart:'U+1E100',	codeEnd:'U+1E14F',	nameCht:'創世紀苗文',	nameEng:'Nyiakeng Puachue Hmong',	description:'創世紀苗文' },
    { plane:'1 SMP',	codeStart:'U+1E290',	codeEnd:'U+1E2BF',	nameCht:'投投文',	nameEng:'Toto',	description:'投投文' },
    { plane:'1 SMP',	codeStart:'U+1E2C0',	codeEnd:'U+1E2FF',	nameCht:'文喬字母',	nameEng:'Wancho',	description:'文喬字母' },
    { plane:'1 SMP',	codeStart:'U+1E4D0',	codeEnd:'U+1E4FF',	nameCht:'蒙達里字母',	nameEng:'Nag Mundari',	description:'蒙達里字母' },
    { plane:'1 SMP',	codeStart:'U+1E7E0',	codeEnd:'U+1E7FF',	nameCht:'衣索比亞字母擴充-B',	nameEng:'Ethiopic Extended-B',	description:'吉茲字母' },
    { plane:'1 SMP',	codeStart:'U+1E800',	codeEnd:'U+1E8DF',	nameCht:'門德基卡庫文',	nameEng:'Mende Kikakui',	description:'門德基卡庫文' },
    { plane:'1 SMP',	codeStart:'U+1E900',	codeEnd:'U+1E95F',	nameCht:'阿德拉姆字母',	nameEng:'Adlam',	description:'阿德拉姆字母' },
    { plane:'1 SMP',	codeStart:'U+1EC70',	codeEnd:'U+1ECBF',	nameCht:'印度西亞格數字',	nameEng:'Indic Siyaq Numbers',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1ED00',	codeEnd:'U+1ED4F',	nameCht:'奧斯曼西亞格數字',	nameEng:'Ottoman Siyaq Numbers',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1EE00',	codeEnd:'U+1EEFF',	nameCht:'阿拉伯字母數字符號',	nameEng:'Arabic Mathematical Alphabetic Symbols',	description:'阿拉伯文' },
    { plane:'1 SMP',	codeStart:'U+1F000',	codeEnd:'U+1F02F',	nameCht:'麻將牌',	nameEng:'Mahjong Tiles',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1F030',	codeEnd:'U+1F09F',	nameCht:'多米諾骨牌',	nameEng:'Domino Tiles',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1F0A0',	codeEnd:'U+1F0FF',	nameCht:'撲克牌',	nameEng:'Playing Cards',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1F100',	codeEnd:'U+1F1FF',	nameCht:'圍繞字母數字補充',	nameEng:'Enclosed Alphanumeric Supplement',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1F200',	codeEnd:'U+1F2FF',	nameCht:'圍繞表意文字補充',	nameEng:'Enclosed Ideographic Supplement',	description:'平假名（1個）、通用（63個）' },
    { plane:'1 SMP',	codeStart:'U+1F300',	codeEnd:'U+1F5FF',	nameCht:'雜項符號和象形文字',	nameEng:'Miscellaneous Symbols and Pictographs',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1F600',	codeEnd:'U+1F64F',	nameCht:'表情符號',	nameEng:'Emoticons',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1F650',	codeEnd:'U+1F67F',	nameCht:'裝飾符號',	nameEng:'Ornamental Dingbats',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1F680',	codeEnd:'U+1F6FF',	nameCht:'交通和地圖符號',	nameEng:'Transport and Map Symbols',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1F700',	codeEnd:'U+1F77F',	nameCht:'鍊金術符號',	nameEng:'Alchemical Symbols',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1F780',	codeEnd:'U+1F7FF',	nameCht:'幾何圖形擴展',	nameEng:'Geometric Shapes Extended',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1F800',	codeEnd:'U+1F8FF',	nameCht:'追加箭頭-C',	nameEng:'Supplemental Arrows-C',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1F900',	codeEnd:'U+1F9FF',	nameCht:'補充符號和象形文字',	nameEng:'Supplemental Symbols and Pictographs',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1FA00',	codeEnd:'U+1FA6F',	nameCht:'棋類符號',	nameEng:'Chess Symbols',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1FA70',	codeEnd:'U+1FAFF',	nameCht:'符號和象形文字擴充-A',	nameEng:'Symbols and Pictographs Extended-A',	description:'通用' },
    { plane:'1 SMP',	codeStart:'U+1FB00',	codeEnd:'U+1FBFF',	nameCht:'遺留計算符號',	nameEng:'Symbols for Legacy Computing',	description:'通用' },
    { plane:'2 SIP',	codeStart:'U+20000',	codeEnd:'U+2A6DF',	nameCht:'中日韓統一表意文字擴充區B',	nameEng:'CJK Unified Ideographs Extension B',	description:'漢字' },
    { plane:'2 SIP',	codeStart:'U+2A700',	codeEnd:'U+2B73F',	nameCht:'中日韓統一表意文字擴充區C',	nameEng:'CJK Unified Ideographs Extension C',	description:'漢字' },
    { plane:'2 SIP',	codeStart:'U+2B740',	codeEnd:'U+2B81F',	nameCht:'中日韓統一表意文字擴充區D',	nameEng:'CJK Unified Ideographs Extension D',	description:'漢字' },
    { plane:'2 SIP',	codeStart:'U+2B820',	codeEnd:'U+2CEAF',	nameCht:'中日韓統一表意文字擴充區E',	nameEng:'CJK Unified Ideographs Extension E',	description:'漢字' },
    { plane:'2 SIP',	codeStart:'U+2CEB0',	codeEnd:'U+2EBEF',	nameCht:'中日韓統一表意文字擴充區F',	nameEng:'CJK Unified Ideographs Extension F',	description:'漢字' },
    { plane:'2 SIP',	codeStart:'U+2EBF0',	codeEnd:'U+2EE5F',	nameCht:'中日韓統一表意文字擴充區I',	nameEng:'CJK Unified Ideographs Extension I',	description:'漢字' },
    { plane:'2 SIP',	codeStart:'U+2F800',	codeEnd:'U+2FA1F',	nameCht:'中日韓相容表意文字補充區',	nameEng:'CJK Compatibility Ideographs Supplement',	description:'漢字' },
    { plane:'3 TIP',	codeStart:'U+30000',	codeEnd:'U+3134F',	nameCht:'中日韓統一表意文字擴充區G',	nameEng:'CJK Unified Ideographs Extension G',	description:'漢字' },
    { plane:'3 TIP',	codeStart:'U+31350',	codeEnd:'U+323AF',	nameCht:'中日韓統一表意文字擴充區H',	nameEng:'CJK Unified Ideographs Extension H',	description:'漢字' },
    { plane:'14 SSP',	codeStart:'U+E0000',	codeEnd:'U+E007F',	nameCht:'標籤',	nameEng:'Tags',	description:'通用' },
    { plane:'14 SSP',	codeStart:'U+E0100',	codeEnd:'U+E01EF',	nameCht:'變體選擇符補充',	nameEng:'Variation Selectors Supplement',	description:'繼承' },
    { plane:'15 PUA-A',	codeStart:'U+F0000',	codeEnd:'U+FFFFF',	nameCht:'補充私人使用區-A',	nameEng:'Supplementary Private Use Area-A',	description:'未知' },
    { plane:'16 PUA-B',	codeStart:'U+100000',	codeEnd:'U+10FFFF',	nameCht:'補充私人使用區-B',	nameEng:'Supplementary Private Use Area-B',	description:'未知' },
]
